name: CI Frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: "testing-url"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "testing-anon-key"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # or 'lts/*' if you want the LTS line
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build

      # Optional: add quality gates
      # - name: Lint
      #   working-directory: frontend
      #   run: npm run lint
      # - name: Type check
      #   working-directory: frontend
      #   run: npm run typecheck
      # - name: Tests
      #   working-directory: frontend
      #   run: npm test -- --ci
