name: CI Frontend

on:
  push:
    branches: [master, "**/*"] # Previews on all branches
  pull_request_target:
    branches: ["master"] # Trigger on all pull requests targeting master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Debug Working Directory
        run: |
          echo "Current working directory: $(pwd)"
          ls -la
          ls -la frontend

      - name: Install dependencies
        working-directory: frontend
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_API_URL: "http://localhost:8000"
          NEXT_PUBLIC_URL: "http://localhost:3000"
        run: npm ci

      - name: Run Tests
        working-directory: frontend
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_API_URL: "http://localhost:8000"
          NEXT_PUBLIC_URL: "http://localhost:3000"
        run: npm test -- --ci --coverage

      - name: Build Frontend
        working-directory: frontend
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_API_URL: "http://localhost:8000"
          NEXT_PUBLIC_URL: "http://localhost:3000"
        run: npm run build
